name: Build and publish dashboards

on:
  schedule:
    - cron: "0 */6 * * *"     # every 6 hours (UTC)
  workflow_dispatch:          # allow manual run from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Lisbon       # show Lisbon time on pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Generate site from newest CSV (or sample)
        run: |
          python scripts/build_site_from_csv.py

      - name: Commit and push artifacts
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add site/ data/
          git commit -m "Auto-build site $(date -u +'%Y-%m-%d %H:%M:%S')" || echo "Nothing to commit"
          git push
